### ISSUE TITLE
pamidb_to_json.py : utf-8 UnicodeDecodeError

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#26]
Hi,

I've got another kind of unusual pamidb_to_json issue: when trying to convert a mer, I'm getting the following error:

```
pamis-iMac:~ pamiaudio$ pamidb_to_json.py -i /Users/pamiaudio/Desktop/scm2144.mer -o /Users/pamiaudio/Desktop/scm2144 
/usr/local/lib/python3.6/site-packages/ami_md/ami_json.py:4: FutureWarning: The pandas.tslib module is deprecated and will be removed in a future version.
  from pandas.tslib import Timestamp
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1162, in pandas._libs.parsers.TextReader._convert_tokens (pandas/_libs/parsers.c:14858)
  File "pandas/_libs/parsers.pyx", line 1273, in pandas._libs.parsers.TextReader._convert_with_dtype (pandas/_libs/parsers.c:17119)
  File "pandas/_libs/parsers.pyx", line 1289, in pandas._libs.parsers.TextReader._string_convert (pandas/_libs/parsers.c:17347)
  File "pandas/_libs/parsers.pyx", line 1524, in pandas._libs.parsers._string_box_utf8 (pandas/_libs/parsers.c:23041)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 66: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pamiaudio/Desktop/ami-tools/bin/pamidb_to_json.py", line 46, in <module>
    main()
  File "/Users/pamiaudio/Desktop/ami-tools/bin/pamidb_to_json.py", line 33, in main
    md = pd.read_csv(args.input, dtype = dtypes)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 655, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 411, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1005, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.6/site-packages/pandas/io/parsers.py", line 1748, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 890, in pandas._libs.parsers.TextReader.read (pandas/_libs/parsers.c:10862)
  File "pandas/_libs/parsers.pyx", line 912, in pandas._libs.parsers.TextReader._read_low_memory (pandas/_libs/parsers.c:11138)
  File "pandas/_libs/parsers.pyx", line 989, in pandas._libs.parsers.TextReader._read_rows (pandas/_libs/parsers.c:12175)
  File "pandas/_libs/parsers.pyx", line 1117, in pandas._libs.parsers.TextReader._convert_column_data (pandas/_libs/parsers.c:14136)
  File "pandas/_libs/parsers.pyx", line 1169, in pandas._libs.parsers.TextReader._convert_tokens (pandas/_libs/parsers.c:14972)
  File "pandas/_libs/parsers.pyx", line 1273, in pandas._libs.parsers.TextReader._convert_with_dtype (pandas/_libs/parsers.c:17119)
  File "pandas/_libs/parsers.pyx", line 1289, in pandas._libs.parsers.TextReader._string_convert (pandas/_libs/parsers.c:17347)
  File "pandas/_libs/parsers.pyx", line 1524, in pandas._libs.parsers._string_box_utf8 (pandas/_libs/parsers.c:23041)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 66: invalid continuation byte
```
I can't figure out exactly what's different about these records (I thought for a minute the issue was due to the way I duped PM records to make EM records--exporting out of Filemaker, opening in LibreOffice, changing PMs to EMs, re-importing into Filemaker--but I don't believe this been an issue in the past). I'll happily share the offending mer...

Thanks!

Ben

**Comment by bturkus** [comment]
False Prophet Ben here. FunMaker Pro exports with "system default" character encodings, in this case Mac Roman. Add encoding="mac-roman" to interpret them, but still need something to turn unicode encodings back into characters, e.g \u2013 is actually - or something like that

**Comment by bturkus** [comment]
hey
this problem kinda reared back up for me. @nkrabben could you take a look for me? sending you the offending mer.

```
MY-LPAMI-056430:ami-tools benjaminturkus$ python3 /Users/benjaminturkus/Desktop/ami-tools/bin/pamidb_to_json.py -i /Users/benjaminturkus/Desktop/nancyreynolds.mer -o /Users/benjaminturkus/Desktop/json 
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1134, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1240, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1256, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1494, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 19: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/benjaminturkus/Desktop/ami-tools/bin/pamidb_to_json.py", line 47, in <module>
    main()
  File "/Users/benjaminturkus/Desktop/ami-tools/bin/pamidb_to_json.py", line 34, in main
    md = pd.read_csv(args.input, dtype = dtypes)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 678, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 446, in _read
    data = parser.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1036, in read
    ret = self._engine.read(nrows)
  File "/usr/local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1848, in read
    data = self._reader.read(nrows)
  File "pandas/_libs/parsers.pyx", line 876, in pandas._libs.parsers.TextReader.read
  File "pandas/_libs/parsers.pyx", line 891, in pandas._libs.parsers.TextReader._read_low_memory
  File "pandas/_libs/parsers.pyx", line 968, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 1094, in pandas._libs.parsers.TextReader._convert_column_data
  File "pandas/_libs/parsers.pyx", line 1141, in pandas._libs.parsers.TextReader._convert_tokens
  File "pandas/_libs/parsers.pyx", line 1240, in pandas._libs.parsers.TextReader._convert_with_dtype
  File "pandas/_libs/parsers.pyx", line 1256, in pandas._libs.parsers.TextReader._string_convert
  File "pandas/_libs/parsers.pyx", line 1494, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8e in position 19: invalid start byte
```

**Comment by nkrabben** [comment]
is this still an issue?

**Comment by bturkus** [comment]
closing for now but will reopen or send new issue if needed
