### ISSUE TITLE
virtual environment for ami-tools

### ISSUE THREAD

**Issue by bturkus** [NYPL/ami-tools#45]
Hi,

Recently I've been experiencing some frustrating python/pip issues...I don't know exactly what's causing the problem or how to resolve it, but It appears that a brew update/upgrade to python 3.9 is triggering this kind of error:

```
MY-PAMI-038536:bin benjaminturkus$ python3 validate_ami_bags.py -h
Traceback (most recent call last):
  File "/Users/benjaminturkus/Desktop/ami-tools/bin/validate_ami_bags.py", line 7, in <module>
    from ami_bag.ami_bag import ami_bag
  File "/usr/local/lib/python3.9/site-packages/ami_bag/ami_bag.py", line 8, in <module>
    from ami_md.ami_excel import ami_excel
  File "/usr/local/lib/python3.9/site-packages/ami_md/ami_excel.py", line 14, in <module>
    import ami_md.ami_json as ami_json
  File "/usr/local/lib/python3.9/site-packages/ami_md/ami_json.py", line 8, in <module>
    import ami_files.ami_file as ami_file
  File "/usr/local/lib/python3.9/site-packages/ami_files/ami_file.py", line 3, in <module>
    from pymediainfo import MediaInfo
ModuleNotFoundError: No module named 'pymediainfo'
```
As far as I can tell, everything is installed correctly and my python path is as it should be, but there's some disconnect that's preventing python from finding the right packages. I'd like to (a) actually learn how to resolve what's going on, but (b) also discuss the possibility of setting up a virtual environment for ami-tools that might potentially future proof us a little bit more and prevent this kind of thing from cropping up.

Any advice or thoughts would be appreciated. 

Thanks,

Ben

**Comment by nkrabben** [comment]
This is an ongoing issue that I'm experimenting with on a fresh computer.

Ideally it would resolve with new installation instructions that use pipenv, but I need to check out if I can use pipenv like that.
